# Remove InferenceService CRD
$patch: delete
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferenceservices.serving.kserve.io
---
# Remove InferenceService MutatingWebhookConfiguration
$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: inferenceservice.serving.kserve.io
---
# Remove InferenceService ValidatingWebhookConfiguration
$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: inferenceservice.serving.kserve.io
---
# Remove TrainedModel CRD
$patch: delete
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trainedmodels.serving.kserve.io
---
# Remove TrainedModel ValidatingWebhookConfiguration
$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: trainedmodel.serving.kserve.io
---
# Remove ServingRuntime CRD
$patch: delete
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servingruntimes.serving.kserve.io
---
# Remove ServingRuntime ValidatingWebhookConfiguration
$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: servingruntime.serving.kserve.io
---
# Remove InferenceGraph CRD
$patch: delete
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferencegraphs.serving.kserve.io
---
# Remove InferenceGraph ValidatingWebhookConfiguration
$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: inferencegraph.serving.kserve.io
---
# Remove ClusterStorageContainer CRD
$patch: delete
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstoragecontainers.serving.kserve.io