apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../components/kserve
- ../../components/llmisvc
# - ../../localmodels

resources:
- ../../base
- user-cluster-roles.yaml
- network-policies.yaml

namespace: opendatahub

patches:
- path: remove-namespace.yaml
- path: remove-cert-manager.yaml
- path: remove-clusterservingruntime-crd.yaml
- path: inferenceservice-config-patch.yaml
- path: set-resources-manager-patch.yaml
- target:
    kind: ValidatingWebhookConfiguration
    name: inferenceservice.serving.kserve.io
  path: openshift-ca-patch.yaml
- target:
    kind: CustomResourceDefinition
    name: inferenceservices.serving.kserve.io
  path: openshift-ca-patch.yaml

replacements:
- source:
    kind: ConfigMap
    name: kserve-parameters
    fieldpath: data.kserve-controller
  targets:
  - select:
      kind: Deployment
      name: kserve-controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].image

configMapGenerator:
- envs:
  - params.env
  name: kserve-parameters

generatorOptions:
  disableNameSuffixHash: true

vars:
- fieldref:
    fieldpath: data.kserve-storage-initializer
  name: kserve-storage-initializer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-agent
  name: kserve-agent
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-router
  name: kserve-router
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kube-rbac-proxy
  name: kube-rbac-proxy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters

configurations:
  - params.yaml
