$patch: delete
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kserve
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: kserve
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: llmisvc-selfsigned-issuer
  namespace: kserve
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llmisvc-serving-certso, we can uncomment
  namespace: kserve
