# This is the ClusterIssuer that OpenDataHub components should use to issue certificates.
# It uses the CA certificate created by ca-certificate.yaml.
# Being cluster-scoped, any namespace can request certificates from this issuer.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: opendatahub-ca-issuer
spec:
  ca:
    secretName: opendatahub-ca