apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Bootstrap: self-signed ClusterIssuer (can be replaced with Vault, etc.)
  - selfsigned-issuer.yaml
  # CA certificate issued by the bootstrap issuer
  - ca-certificate.yaml
  # ClusterIssuer using the CA (workloads request certs from this)
  - ca-issuer.yaml